# Generated by Django 5.1.3 on 2025-02-11 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ocupação Padrão', max_length=100, verbose_name='Nome da Ocupação')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('FUNCIONARIO', 'Funcionário'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Função')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, default='00 0 0000-0000', max_length=15, null=True, verbose_name='Telefone')),
                ('address', models.CharField(default='Default Address', max_length=200, verbose_name='Endereço')),
                ('neighborhood', models.CharField(default='Centro', max_length=100, verbose_name='Bairro')),
                ('number', models.CharField(default='000', max_length=10, verbose_name='Número')),
                ('urban_or_rural', models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], default='Urbano', max_length=10, verbose_name='Zona')),
                ('city', models.CharField(default='Muzambinho-MG', max_length=100, verbose_name='Cidade')),
                ('emergency_phone', models.CharField(default='00 0 0000-0000', max_length=15, verbose_name='Telefone de Emergência')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nome Padrão', max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(default='Sobrenome Padrão', max_length=100, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('mother_name', models.CharField(default='Nome da Mãe Padrão', max_length=100, verbose_name='Nome da Mãe')),
                ('father_name', models.CharField(default='Nome do Pai Padrão', max_length=100, verbose_name='Nome do Pai')),
                ('address', models.CharField(default='Endereço Padrão', max_length=200, verbose_name='Endereço')),
                ('neighborhood', models.CharField(default='Centro', max_length=100, verbose_name='Bairro')),
                ('number', models.CharField(default='000', max_length=10, verbose_name='Número')),
                ('urban_or_rural', models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], default='Urbano', max_length=10, verbose_name='Zona')),
                ('city', models.CharField(default='Muzambinho-MG', max_length=100, verbose_name='Cidade')),
                ('emergency_phone', models.CharField(default='00 0 0000-0000', max_length=15, verbose_name='Telefone de Emergência')),
                ('photo', models.ImageField(upload_to='fotos/estudantes/', verbose_name='Foto')),
                ('enrollment_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Matrícula')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Modelo Padrão', max_length=100, verbose_name='Modelo')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('action', models.CharField(default='Ação Padrão', max_length=50, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Salário')),
                ('admission', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Admissão')),
                ('resignation', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Demissão')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fotos/funcionarios/', verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.occupation', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título Padrão', max_length=100, verbose_name='Título')),
                ('file', models.FileField(upload_to='docs/funcionarios/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Documento do Funcionário',
                'verbose_name_plural': 'Documentos dos Funcionários',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título Padrão', max_length=100, verbose_name='Título')),
                ('file', models.FileField(upload_to='docs/estudantes/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Documento do Estudante',
                'verbose_name_plural': 'Documentos dos Estudantes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nome da Turma Padrão', max_length=100, verbose_name='Nome')),
                ('shift', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=20, verbose_name='Turno')),
                ('image', models.ImageField(upload_to='fotos/turmas/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Professor')),
                ('students', models.ManyToManyField(related_name='classes', to='app.students', verbose_name='Estudantes')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.profile')),
                ('photo', models.ImageField(upload_to='pais/', verbose_name='Foto')),
                ('son', models.ManyToManyField(related_name='parents', to='app.students', verbose_name='Filhos')),
            ],
            options={
                'verbose_name': 'Pai/Mãe',
                'verbose_name_plural': 'Pais/Mães',
                'ordering': ['user__username'],
            },
            bases=('app.profile',),
        ),
        migrations.CreateModel(
            name='DocumentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título Padrão', max_length=100, verbose_name='Título')),
                ('file', models.FileField(upload_to='docs/pais/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parents', verbose_name='Pai/Mãe')),
            ],
            options={
                'verbose_name': 'Documento do Pai/Mãe',
                'verbose_name_plural': 'Documentos dos Pais/Mães',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('notes', models.TextField(blank=True, default='Sem observações', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.class', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.students', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Registro de Frequência',
                'verbose_name_plural': 'Registros de Frequência',
                'ordering': ['-date'],
                'unique_together': {('turma', 'student', 'date')},
            },
        ),
    ]
